---
name: pre-commit

on:
  push:
  pull_request:
    branches: ["main"]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install ansible-lint and collections
        run: |
          pip install ansible-lint
          ansible-galaxy collection install community.general

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1
